name: Deploy Orders Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Export from poetry to requirements.txt
        uses: divideprojects/poetry-export-requirements-action@v1
        with:
          without-hashes: true
          outfile-name: src/requirements.txt

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy orders-bot \
            --timeout=360s \
            --runtime python310 \
            --source src \
            --trigger-http \
            --entry-point handle_update \
            --allow-unauthenticated \
            --region us-east1 \
            --project yonidev \
            --set-env-vars BOT_TOKEN=${{ secrets.BOT_TOKEN }}
