name: Deploy Cloud Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - run: pip install telegram

      - name: Build and deploy Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: orders-bot
          runtime: python311
          entry_point: main.handle_update
          trigger_http: true
          env_vars: BOT_TOKEN=${{ secrets.BOT_TOKEN }}