name: Deploy Cloud Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: pip install telegram

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy orders-bot \
            --runtime python310 \
            --trigger-http \
            --entry-point handle_update \
            --allow-unauthenticated \
            --region us-east1 \
            --project yonidev